openapi: 3.0.0
info:
  title: Techkids Software Web API
  description: Web API
  contact:
    email: thinhtran@techkids.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: http://localhost:3000/api
  description: Local server
- url: https://cindidev.mindxtech.com/api
  description: Development server ( Testing data )
