export const PERMISSIONS = Object.freeze({
  NOTIFICATION: {
    VIEW: 'NOTIFICATION.VIEW',
    CREATE: 'NOTIFICATION.CREATE',
    EDIT: 'NOTIFICATION.EDIT',
    DELETE: 'NOTIFICATION.DELETE',
  },
});
